# This is a build/test script for "travis-ci", a continuous
# integration website that will build and test this project
# every time something is submitted, and send me email if
# the test breaks
language: c

os:
  - linux
  - osx
  
compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y libpcap-dev; fi

script:
  - make test


